"""Access-owned ports. Implementations are selected only by runtime composition."""

from typing import Protocol

from app.contexts.access.application.models import LoginAttempt, TokenPair, WorkspaceBinding
from app.contexts.access.domain.principal import BrowserSession, Principal


class EphemeralStore(Protocol):
    async def put(self, purpose: str, key: str, value: str, ttl: int) -> None: ...
    async def get(self, purpose: str, key: str) -> str | None: ...
    async def take(self, purpose: str, key: str) -> str | None: ...
    async def remove(self, purpose: str, key: str) -> None: ...
    async def consume_once(self, key: str, ttl: int) -> bool: ...


class TokenVerifier(Protocol):
    async def access_token(self, token: str) -> Principal: ...
    async def id_token(
        self, token: str, client_id: str, nonce: str, access_token: str, principal: Principal
    ) -> int: ...


class ProofVerifier(Protocol):
    async def verify(
        self, proof: str, access_token: str, jkt: str, method: str, uri: str
    ) -> None: ...


class AuthorizationCodeClient(Protocol):
    def authorization_url(self, verifier: str, state: str, nonce: str, scopes: str) -> str: ...
    async def redeem(self, code: str, verifier: str) -> TokenPair: ...


class BrowserStateStore(Protocol):
    async def put_attempt(self, key: str, attempt: LoginAttempt, ttl: int) -> None: ...
    async def take_attempt(self, key: str) -> LoginAttempt | None: ...
    async def put_session(self, handle: str, session: BrowserSession, ttl: int) -> None: ...
    async def get_session(self, handle: str) -> BrowserSession | None: ...
    async def remove_session(self, handle: str) -> None: ...


class WorkspaceBindings(Protocol):
    async def find(self, issuer: str, organization: str) -> WorkspaceBinding | None: ...
    async def workspace_exists(self, workspace_id: str) -> bool: ...
    async def workspace_is_bound(self, workspace_id: str) -> bool: ...
    async def create_workspace(self, name: str) -> str: ...
    async def insert(self, issuer: str, organization: str, workspace_id: str) -> None: ...
    async def set_active(self, issuer: str, organization: str, active: bool) -> None: ...
