"""The only ephemeral-state operations needed by login, sessions and DPoP."""

from typing import Protocol


class EphemeralStore(Protocol):
    async def put(self, purpose: str, key: str, value: str, ttl: int) -> None: ...
    async def get(self, purpose: str, key: str) -> str | None: ...
    async def take(self, purpose: str, key: str) -> str | None: ...
    async def remove(self, purpose: str, key: str) -> None: ...
    async def consume_once(self, key: str, ttl: int) -> bool: ...
