[flyway]
locations = ["filesystem:migrations"]
callbackLocations = ["filesystem:callbacks"]
defaultSchema = "links_migrations"
createSchemas = true
table = "flyway_schema_history"
group = true
lockRetryCount = 50
executeInTransaction = true
mixed = false
baselineOnMigrate = false
outOfOrder = false
ignoreMigrationPatterns = []
validateMigrationNaming = true
validateOnMigrate = true
cleanDisabled = true
target = "5"

[environments.default]
schemas = ["links_migrations"]
